# Generated by Django 5.1 on 2024-08-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepic',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
